version: '3'

services:
  app:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      - PORT=8080
      - DB_URL=postgres://postgres:root@db:5432/task2?sslmode=disable
      - SECRET=SEDKHG776RFYGI986GHKNV
      - EMAIL_SENDER=s11924224@stu.najah.edu
      - EMAIL_PASSWORD=nxiu geqb peri kyai
      - TOKEN_EXPIRATION=2592000
      - base_url=http://localhost:8081/api/v1
    networks:
      - app-network

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=task2
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: